/*
 * platform_config.h
 * 多点温度/环境监测系统的集中配置文件。这里统一保存时钟、蓝牙串口、
 * 采样周期、报警阈值和记录容量，避免应用逻辑中散落硬编码参数。
 */
#ifndef PLATFORM_CONFIG_H
#define PLATFORM_CONFIG_H

#include <stdint.h>

/* PLAYER_FIRMWARE_NAME: 蓝牙 info 命令返回的工程名称。 */
#define PLAYER_FIRMWARE_NAME            "MSP430F5529-ENV-MON"

/* PLAYER_FIRMWARE_VERSION: 手动维护的软件版本号。 */
#define PLAYER_FIRMWARE_VERSION         "2.0.0"

/* PLAYER_HARDWARE_PROFILE: 蓝牙 wiring 命令返回的主要接线摘要。 */
#define PLAYER_HARDWARE_PROFILE         "DHT:P1.0 MQ2:P6.0 US:P1.2/1.3 OLED:P3.0/3.1 BT:UCA1"

/* MCLK_HZ: CPU clock frequency used by delay loops and timing calculations. */
#define MCLK_HZ                         16000000UL

/* SMCLK_HZ: Sub-main clock frequency used by Timer_A and serial peripherals. */
#define SMCLK_HZ                        16000000UL

/* BOARD_TICK_HZ: 1 ms system tick rate generated by Timer0_A0. */
#define BOARD_TICK_HZ                   1000UL

/* PLAYER_BT_UART_UCA1_P45: Bluetooth option using UCA1 TX=P4.4, RX=P4.5. */
#define PLAYER_BT_UART_UCA1_P45         1

/* PLAYER_BT_UART_UCA0_P34: Bluetooth option using UCA0 TX=P3.3, RX=P3.4. */
#define PLAYER_BT_UART_UCA0_P34         2

/*
 * Course handout lists HC-05 on P3.3/P3.4, but P3.3 is also listed as TF-card
 * MISO. The default build uses UCA1 on P4.4/P4.5 so SD and Bluetooth can both
 * run at the same time. Change to PLAYER_BT_UART_UCA0_P34 only if the TF MISO
 * wiring is moved or Bluetooth TX is intentionally not connected.
 */
#define PLAYER_BT_UART_MODE             PLAYER_BT_UART_UCA1_P45

/* ENV_SAMPLE_PERIOD_MS: 三类传感器的周期采样间隔。 */
#define ENV_SAMPLE_PERIOD_MS            1000u

/* ENV_OLED_REFRESH_MS: OLED 页面刷新间隔。 */
#define ENV_OLED_REFRESH_MS             500u

/* ENV_BT_PUSH_MS: 蓝牙主动上传实时数据的间隔。 */
#define ENV_BT_PUSH_MS                  2000u

/* ENV_FLASH_LOG_MS: 内部 Flash 历史记录写入间隔。 */
#define ENV_FLASH_LOG_MS                10000u

/* ENV_DEFAULT_TEMP_THRESHOLD_X10: 默认温度报警阈值，单位 0.1 摄氏度。 */
#define ENV_DEFAULT_TEMP_THRESHOLD_X10  300

/* ENV_TEMP_STEP_X10: 编码器和 T+/T- 命令每次调整的阈值步进。 */
#define ENV_TEMP_STEP_X10               5

/* ENV_GAS_WARN_ADC: MQ-2 ADC 原始值超过该值后进入气体报警区。 */
#define ENV_GAS_WARN_ADC                1800u

/* ENV_GAS_STEP_ADC: 气体报警等级每升一级对应的 ADC 增量。 */
#define ENV_GAS_STEP_ADC                300u

/* ENV_TRACE_DEPTH: 近期蓝牙/编码器操作轨迹条数。 */
#define ENV_TRACE_DEPTH                 6u

/* ENCODER_POLL_PERIOD_MS: EC11 sample interval for quadrature decoding. */
#define ENCODER_POLL_PERIOD_MS          2u

/* ENCODER_DEBOUNCE_TICKS: stable samples required for the EC11 push button. */
#define ENCODER_DEBOUNCE_TICKS          5u

/* ENCODER_LONG_PRESS_MS: EC11 hold time that emits the long-press event. */
#define ENCODER_LONG_PRESS_MS           800u

/* ENCODER_LONG_PRESS_TICKS: EC11 long-press threshold expressed in polls. */
#define ENCODER_LONG_PRESS_TICKS        (ENCODER_LONG_PRESS_MS / ENCODER_POLL_PERIOD_MS)

/* LOCAL_BUTTON_POLL_PERIOD_MS: S1/S2/S4 scan interval. */
#define LOCAL_BUTTON_POLL_PERIOD_MS     5u

/* LOCAL_BUTTON_DEBOUNCE_TICKS: stable scans required before a button event. */
#define LOCAL_BUTTON_DEBOUNCE_TICKS     4u

/* LOCAL_BUTTON_LONG_PRESS_MS: hold time that promotes a local key to long press. */
#define LOCAL_BUTTON_LONG_PRESS_MS      800u

/* LOCAL_BUTTON_LONG_PRESS_TICKS: long-press threshold expressed in button polls. */
#define LOCAL_BUTTON_LONG_PRESS_TICKS   (LOCAL_BUTTON_LONG_PRESS_MS / LOCAL_BUTTON_POLL_PERIOD_MS)

#endif
