/*
 * platform_config.h
 * Central compile-time configuration for the MSP430F5529 Bluetooth WAV player.
 * This file keeps clock rates, command defaults, buffer sizes, and selectable
 * hardware mappings in one place so board changes do not leak into application
 * logic.
 */
#ifndef PLATFORM_CONFIG_H
#define PLATFORM_CONFIG_H

#include <stdint.h>

/* PLAYER_FIRMWARE_NAME: ASCII product name reported by the info command. */
#define PLAYER_FIRMWARE_NAME            "MSP430F5529-BT-WAV"

/* PLAYER_FIRMWARE_VERSION: manually updated firmware version string. */
#define PLAYER_FIRMWARE_VERSION         "1.4.1"

/* PLAYER_HARDWARE_PROFILE: wiring profile name reported for lab debugging. */
#define PLAYER_HARDWARE_PROFILE         "TF:P3.1-3.3 I2S:P4.1-4.3 BT:UCA1"

/* MCLK_HZ: CPU clock frequency used by delay loops and timing calculations. */
#define MCLK_HZ                         16000000UL

/* SMCLK_HZ: Sub-main clock frequency used by Timer_A and serial peripherals. */
#define SMCLK_HZ                        16000000UL

/* BOARD_TICK_HZ: 1 ms system tick rate generated by Timer0_A0. */
#define BOARD_TICK_HZ                   1000UL

/* PLAYER_BT_UART_UCA1_P45: Bluetooth option using UCA1 TX=P4.4, RX=P4.5. */
#define PLAYER_BT_UART_UCA1_P45         1

/* PLAYER_BT_UART_UCA0_P34: Bluetooth option using UCA0 TX=P3.3, RX=P3.4. */
#define PLAYER_BT_UART_UCA0_P34         2

/*
 * Course handout lists HC-05 on P3.3/P3.4, but P3.3 is also listed as TF-card
 * MISO. The default build uses UCA1 on P4.4/P4.5 so SD and Bluetooth can both
 * run at the same time. Change to PLAYER_BT_UART_UCA0_P34 only if the TF MISO
 * wiring is moved or Bluetooth TX is intentionally not connected.
 */
#define PLAYER_BT_UART_MODE             PLAYER_BT_UART_UCA1_P45

/* PLAYER_AUTOPLAY_ON_BOOT: nonzero starts the first valid WAV after boot. */
#define PLAYER_AUTOPLAY_ON_BOOT         1u

/* PLAYER_DEFAULT_VOLUME: startup volume, scaled against PLAYER_VOLUME_MAX. */
#define PLAYER_DEFAULT_VOLUME           18u

/* PLAYER_VOLUME_MAX: maximum software gain step accepted by the player. */
#define PLAYER_VOLUME_MAX               32u

/* PLAYER_MAX_TRACKS: highest TRACKxx.WAV number scanned on the TF card. */
#define PLAYER_MAX_TRACKS               9u

/* PLAYER_AUDIO_BUFFER_BYTES: one SD read chunk; keep small for MSP430 RAM. */
#define PLAYER_AUDIO_BUFFER_BYTES       192u

/* PLAYER_TEST_TONE_FRAMES: stereo frames emitted by the DAC self-test command. */
#define PLAYER_TEST_TONE_FRAMES         900u

/* PLAYER_TEST_TONE_AMPLITUDE: signed PCM amplitude used by the DAC self-test. */
#define PLAYER_TEST_TONE_AMPLITUDE      12000

/* PLAYER_STATUS_PUSH_MS: periodic Bluetooth status interval; 0 disables it. */
#define PLAYER_STATUS_PUSH_MS           5000u

/* PLAYER_LED_PLAYING_MS: status LED toggle period while audio is playing. */
#define PLAYER_LED_PLAYING_MS           200u

/* PLAYER_LED_PAUSED_MS: status LED toggle period while playback is paused. */
#define PLAYER_LED_PAUSED_MS            1000u

/* PLAYER_LED_ERROR_STEP_MS: status LED step period for error double-blink. */
#define PLAYER_LED_ERROR_STEP_MS        150u

/* PLAYER_ENABLE_EPAPER_PANEL: 1 enables optional 296x128 SPI e-paper output. */
#define PLAYER_ENABLE_EPAPER_PANEL      0u

/*
 * PLAYER_EPAPER_REFRESH_ON_CHANGE: nonzero refreshes the optional e-paper
 * panel whenever the display model is reported. Keep PLAYER_ENABLE_EPAPER_PANEL
 * at 0 unless the P6.x wiring is actually added, because e-paper refresh is slow.
 */
#define PLAYER_EPAPER_REFRESH_ON_CHANGE 1u

/* ENCODER_POLL_PERIOD_MS: EC11 sample interval for quadrature decoding. */
#define ENCODER_POLL_PERIOD_MS          2u

/* ENCODER_DEBOUNCE_TICKS: stable samples required for the EC11 push button. */
#define ENCODER_DEBOUNCE_TICKS          5u

/* ENCODER_LONG_PRESS_MS: EC11 hold time that emits the long-press event. */
#define ENCODER_LONG_PRESS_MS           800u

/* ENCODER_LONG_PRESS_TICKS: EC11 long-press threshold expressed in polls. */
#define ENCODER_LONG_PRESS_TICKS        (ENCODER_LONG_PRESS_MS / ENCODER_POLL_PERIOD_MS)

/* LOCAL_BUTTON_POLL_PERIOD_MS: S1/S2/S4 scan interval. */
#define LOCAL_BUTTON_POLL_PERIOD_MS     5u

/* LOCAL_BUTTON_DEBOUNCE_TICKS: stable scans required before a button event. */
#define LOCAL_BUTTON_DEBOUNCE_TICKS     4u

/* LOCAL_BUTTON_LONG_PRESS_MS: hold time that promotes a local key to long press. */
#define LOCAL_BUTTON_LONG_PRESS_MS      800u

/* LOCAL_BUTTON_LONG_PRESS_TICKS: long-press threshold expressed in button polls. */
#define LOCAL_BUTTON_LONG_PRESS_TICKS   (LOCAL_BUTTON_LONG_PRESS_MS / LOCAL_BUTTON_POLL_PERIOD_MS)

#endif
