"""Validate the APK's offline Demo RX transcript.

The real button injects representative firmware response lines into
MainActivity's normal parser, so a phone can show the complete UI effect before
HC-05 pairing or board flashing. This script reads the Java source transcript
and checks that the same lines drive the host-side Android parser model.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from android_ui_parser_sim import AndroidUiState, handle_incoming_text


ROOT = Path(__file__).resolve().parents[1]
MAIN_ACTIVITY = ROOT / "android" / "app" / "src" / "main" / "java" / "com" / "dkjsiogu" / "mspbluetooth" / "MainActivity.java"
DEFAULT_REPORT = ROOT / "docs" / "android_offline_demo_report.md"


def extract_demo_rx_lines(source: str) -> list[str]:
    """Returns the Java DEMO_RX_LINES string literals in source order."""

    block_match = re.search(r"DEMO_RX_LINES\s*=\s*new String\[\]\{(.*?)\n\s*\};", source, re.S)
    if not block_match:
        raise AssertionError("MainActivity.java must define DEMO_RX_LINES")
    return re.findall(r'"([^"]*)"', block_match.group(1))


def run_offline_demo() -> tuple[AndroidUiState, list[str]]:
    """Runs the APK offline transcript through the Android parser model."""

    source = MAIN_ACTIVITY.read_text(encoding="utf-8")
    for marker in [
        'commandButton("Demo RX"',
        "runOfflineDemo",
        "DEMO_RX_LINES",
        'appendLog("demo rx start")',
        'appendLog("demo rx done")',
        "handleIncomingText(builder.toString())",
    ]:
        if marker not in source:
            raise AssertionError(f"MainActivity.java missing offline demo marker: {marker}")

    lines = extract_demo_rx_lines(source)
    if len(lines) < 12:
        raise AssertionError(f"offline demo transcript is too short: {len(lines)} lines")

    state = AndroidUiState()
    handle_incoming_text(state, "".join(f"{line}\r\n" for line in lines))

    if state.dashboard_text != "Mode: playing\nTrack: 3\nVolume: 19\nOrder: repeat_one\nProgress: 42%":
        raise AssertionError(f"offline demo dashboard mismatch: {state.dashboard_text!r}")
    if state.volume_bar != 19 or state.progress_bar != 42:
        raise AssertionError(f"offline demo bars mismatch: volume={state.volume_bar}, progress={state.progress_bar}")
    if "SD:OK" not in state.health_text or "Tone:done" not in state.health_text or "File:TRACK03.WAV" not in state.health_text:
        raise AssertionError(f"offline demo health mismatch: {state.health_text!r}")
    if state.display_text != "Display frame\nplaying T3 V19 ONE\nSD:OK WAV:OPEN\n16000Hz 2ch P42%":
        raise AssertionError(f"offline demo display mismatch: {state.display_text!r}")
    if "1: ok" not in state.track_list_text or "3: ok" not in state.track_list_text:
        raise AssertionError(f"offline demo tracks mismatch: {state.track_list_text!r}")
    if "RX: 15" not in state.link_text or "Last: k" not in state.link_text:
        raise AssertionError(f"offline demo link mismatch: {state.link_text!r}")
    if "EC11 CW:3" not in state.input_text or "S4:1/1" not in state.input_text:
        raise AssertionError(f"offline demo input mismatch: {state.input_text!r}")
    if "bt:trace" not in state.trace_text or "bt:track" not in state.trace_text:
        raise AssertionError(f"offline demo trace mismatch: {state.trace_text!r}")
    if "BT: tx=P4.4 rx=P4.5" not in state.wiring_text:
        raise AssertionError(f"offline demo wiring mismatch: {state.wiring_text!r}")
    if not state.acceptance_text.startswith("Acceptance 9/9"):
        raise AssertionError(f"offline demo acceptance mismatch: {state.acceptance_text!r}")
    if not state.hardware_text.startswith("Hardware 7/9"):
        raise AssertionError(f"offline demo hardware summary mismatch: {state.hardware_text!r}")
    if state.rx_line_buffer:
        raise AssertionError(f"offline demo left partial RX data: {state.rx_line_buffer!r}")

    return state, lines


def row(columns: list[object]) -> str:
    """Formats one Markdown table row."""

    return "| " + " | ".join(str(column).replace("|", "\\|").replace("\n", " / ") for column in columns) + " |"


def render_report(state: AndroidUiState, lines: list[str]) -> str:
    """Renders a concise report for the offline APK demo transcript."""

    return "\n".join(
        [
            "# Android Offline Demo Report",
            "",
            "Generated by `tools/android_offline_demo_sim.py`. It verifies the APK `Demo RX` button source transcript. The button feeds representative firmware response lines into the same parser used by the HC-05 receive thread, so the phone can demonstrate visible effects without a paired module or powered board. Physical Bluetooth, TF-card, DAC, and amplifier behavior still require hardware.",
            "",
            row(["Item", "Evidence"]),
            row(["---", "---"]),
            row(["Transcript lines", len(lines)]),
            row(["Final dashboard", state.dashboard_text]),
            row(["Visual bars", f"volume={state.volume_bar}/32 progress={state.progress_bar}/100"]),
            row(["Health panel", state.health_text]),
            row(["Display frame", state.display_text]),
            row(["Track list", state.track_list_text]),
            row(["Link diagnostics", state.link_text]),
            row(["Input diagnostics", state.input_text]),
            row(["Trace diagnostics", state.trace_text]),
            row(["Wiring diagnostics", state.wiring_text]),
            row(["Acceptance summary", state.acceptance_text]),
            row(["Hardware summary", state.hardware_text]),
            "",
            "## Demo Transcript",
            "",
            "```text",
            *lines,
            "```",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT, help="Markdown report path")
    args = parser.parse_args()

    state, lines = run_offline_demo()
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(render_report(state, lines), encoding="utf-8", newline="\n")

    print("Android offline demo simulation passed")
    print(state.dashboard_text.replace("\n", " | "))
    print(f"Bars volume={state.volume_bar}/32 progress={state.progress_bar}/100")
    print(state.health_text.replace("\n", " | "))
    print(state.display_text.replace("\n", " | "))
    print(state.acceptance_text.replace("\n", " | "))
    print(state.hardware_text.replace("\n", " | "))
    print(f"offline demo report generated: {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
