"""Simulate the APK Run Acceptance button and validate its saved log.

The real APK sends single-character HC-05 commands and appends TX markers to
the phone log. This script models that button path, feeds firmware responses
into the Android parser model, then reuses the serial transcript checker so the
generated phone log proves the same evidence expected from a real classroom
capture.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

from android_ui_parser_sim import AndroidUiState, handle_incoming_text
from bluetooth_protocol_sim import SimulatedPlayer
from serial_acceptance_check import check_required_criteria, check_state_command_snapshots, normalize_lines


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_LOG = ROOT / "dist" / "verification" / "android_acceptance_log.txt"
DEFAULT_REPORT = ROOT / "docs" / "android_acceptance_script_report.md"

ACCEPTANCE_COMMANDS = ["h", "i", "e", "l", "d", "?", "t", "1", "p", "+", "n", "b", "o", "3"]


@dataclass
class AcceptanceResult:
    log_lines: list[str]
    dashboard: str
    display: str
    tracks: str
    passed_checks: int
    total_checks: int


def fragmented_android_feed(android: AndroidUiState, responses: list[str]) -> None:
    """Feeds firmware response lines to the Android parser in small chunks."""

    stream = "".join(f"{line}\r\n" for line in responses)
    index = 0
    for size in (5, 13, 29, 7, 41):
        if index >= len(stream):
            return
        handle_incoming_text(android, stream[index : index + size])
        index += size
    if index < len(stream):
        handle_incoming_text(android, stream[index:])


def run_acceptance_flow() -> AcceptanceResult:
    """Runs the simulated APK acceptance button against the protocol model."""

    player = SimulatedPlayer()
    android = AndroidUiState()
    log_lines = ["connected", "sd mounted", "open TRACK01.WAV", "acceptance start"]

    for command in ACCEPTANCE_COMMANDS:
        before = len(player.transcript)
        log_lines.append(f"TX> {command}")
        player.send(command)
        responses = player.transcript[before:]
        log_lines.extend(responses)
        fragmented_android_feed(android, responses)

    log_lines.append("acceptance commands sent")

    serial_lines = normalize_lines("\n".join(log_lines))
    check_results = check_required_criteria(serial_lines) + check_state_command_snapshots(serial_lines)
    failures = [result for result in check_results if not result.passed]
    if failures:
        raise AssertionError(f"acceptance log failed serial checks: {[failure.label for failure in failures]}")
    if "Mode: playing" not in android.dashboard_text or "Track: 3" not in android.dashboard_text:
        raise AssertionError(f"Android dashboard did not reach final track 3 state: {android.dashboard_text!r}")
    if "playing T3" not in android.display_text:
        raise AssertionError(f"Android display frame did not mirror final track 3 state: {android.display_text!r}")
    if "1: ok" not in android.track_list_text or "3: ok" not in android.track_list_text:
        raise AssertionError(f"Android track list did not parse available tracks: {android.track_list_text!r}")

    return AcceptanceResult(
        log_lines=log_lines,
        dashboard=android.dashboard_text,
        display=android.display_text,
        tracks=android.track_list_text,
        passed_checks=len(check_results),
        total_checks=len(check_results),
    )


def row(columns: list[object]) -> str:
    """Formats one Markdown table row."""

    return "| " + " | ".join(str(column).replace("|", "\\|").replace("\n", " / ") for column in columns) + " |"


def render_report(result: AcceptanceResult, log_path: Path) -> str:
    """Renders a Markdown report for the APK acceptance script simulation."""

    lines = [
        "# Android Acceptance Script Report",
        "",
        "Generated by `tools/android_acceptance_log_sim.py`. It models the APK `Run Acceptance` button: the phone sends diagnostic, display, tone, and playback commands with `TX>` markers, parses the firmware responses into visible panels, and produces a saved log that passes the serial transcript checker. Real phone pairing and board-level audio still require hardware.",
        "",
        row(["Item", "Evidence"]),
        row(["---", "---"]),
        row(["Command sequence", "`" + " ".join(ACCEPTANCE_COMMANDS) + "`"]),
        row(["Saved log", f"`{log_path}`"]),
        row(["Serial transcript checks", f"{result.passed_checks}/{result.total_checks} passed"]),
        row(["Final dashboard", result.dashboard]),
        row(["Final display", result.display]),
        row(["Track list", result.tracks]),
        "",
        "## Log Preview",
        "",
        "```text",
        *result.log_lines[:90],
        "```",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--log", type=Path, default=DEFAULT_LOG, help="Generated Android log path")
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT, help="Markdown report path")
    args = parser.parse_args()

    result = run_acceptance_flow()
    args.log.parent.mkdir(parents=True, exist_ok=True)
    args.log.write_text("\n".join(result.log_lines) + "\n", encoding="utf-8", newline="\n")
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(render_report(result, args.log), encoding="utf-8", newline="\n")

    print("Android acceptance script simulation passed")
    print(result.dashboard.replace("\n", " | "))
    print(f"acceptance log generated: {args.log}")
    print(f"acceptance report generated: {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
