"""Simulate the APK Run Hardware Check button.

The real button is meant for board bring-up: after HC-05 connection it sends a
short diagnostic command sequence and renders a Hardware X/9 evidence summary.
This host-side check keeps that Android workflow tied to the firmware protocol
model before anyone flashes or pairs real hardware.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from android_ui_parser_sim import AndroidUiState, handle_incoming_text, mark_connected, mark_tx
from bluetooth_protocol_sim import SimulatedPlayer


ROOT = Path(__file__).resolve().parents[1]
MAIN_ACTIVITY = ROOT / "android" / "app" / "src" / "main" / "java" / "com" / "dkjsiogu" / "mspbluetooth" / "MainActivity.java"
DEFAULT_REPORT = ROOT / "docs" / "android_hardware_check_report.md"


def extract_hardware_commands(source: str) -> list[str]:
    """Returns the Java HARDWARE_CHECK_COMMANDS string literals in source order."""

    block_match = re.search(r"HARDWARE_CHECK_COMMANDS\s*=\s*new String\[\]\s*\{([^}]*)\}", source, re.S)
    if not block_match:
        raise AssertionError("MainActivity.java must define HARDWARE_CHECK_COMMANDS")
    return re.findall(r'"([^"]*)"', block_match.group(1))


def fragmented_feed(android: AndroidUiState, responses: list[str]) -> None:
    """Feeds firmware response lines through the same fragmented receive path."""

    stream = "".join(f"{line}\r\n" for line in responses)
    for index in range(0, len(stream), 17):
        handle_incoming_text(android, stream[index : index + 17])


def run_hardware_check() -> tuple[AndroidUiState, list[str], list[str]]:
    """Runs the Java-defined hardware check sequence against the player model."""

    source = MAIN_ACTIVITY.read_text(encoding="utf-8")
    for marker in (
        'commandButton("Run Hardware Check"',
        "runHardwareCheck",
        "hardwareView",
        "Hardware 0/9",
        "renderHardwareSummary",
    ):
        if marker not in source:
            raise AssertionError(f"MainActivity.java missing hardware-check marker: {marker}")

    commands = extract_hardware_commands(source)
    expected = ["?", "i", "l", "d", "t", "k", "u", "x", "w"]
    if commands != expected:
        raise AssertionError(f"hardware check commands changed unexpectedly: {commands!r}")

    android = AndroidUiState()
    player = SimulatedPlayer()
    log_lines = ["connected", "hardware check start"]
    mark_connected(android)

    for command in commands:
        before = len(player.transcript)
        log_lines.append(f"TX> {command}")
        mark_tx(android)
        player.send(command)
        responses = player.transcript[before:]
        log_lines.extend(responses)
        fragmented_feed(android, responses)

    log_lines.append("hardware check commands sent")

    if not android.hardware_text.startswith("Hardware 9/9"):
        raise AssertionError(f"hardware summary did not reach 9/9: {android.hardware_text!r}")
    if "Mode:" not in android.dashboard_text or "Progress:" not in android.dashboard_text:
        raise AssertionError(f"dashboard was not populated: {android.dashboard_text!r}")
    if "RX:" not in android.link_text or "Last:" not in android.link_text:
        raise AssertionError(f"link diagnostics were not populated: {android.link_text!r}")
    if "Trace" not in android.trace_text or "bt:trace" not in android.trace_text:
        raise AssertionError(f"trace diagnostics were not populated: {android.trace_text!r}")
    if "BT: tx=P4.4 rx=P4.5" not in android.wiring_text:
        raise AssertionError(f"wiring diagnostics were not populated: {android.wiring_text!r}")

    return android, commands, log_lines


def row(columns: list[object]) -> str:
    """Formats one Markdown table row."""

    return "| " + " | ".join(str(column).replace("|", "\\|").replace("\n", " / ") for column in columns) + " |"


def render_report(android: AndroidUiState, commands: list[str], log_lines: list[str]) -> str:
    """Renders the hardware-check simulation report."""

    return "\n".join(
        [
            "# Android Hardware Check Report",
            "",
            "Generated by `tools/android_hardware_check_sim.py`. It simulates the APK `Run Hardware Check` button against the firmware protocol model. This proves the phone-side workflow and expected HC-05 transcript shape; physical audio, TF-card wiring, and EC11 behavior still require the MSP430F5529 board.",
            "",
            row(["Item", "Evidence"]),
            row(["---", "---"]),
            row(["Command sequence", "`" + " ".join(commands) + "`"]),
            row(["Hardware summary", android.hardware_text]),
            row(["Dashboard", android.dashboard_text]),
            row(["Health", android.health_text]),
            row(["Tracks", android.track_list_text]),
            row(["Link", android.link_text]),
            row(["Input", android.input_text]),
            row(["Trace", android.trace_text]),
            row(["Wiring", android.wiring_text]),
            "",
            "## Log Preview",
            "",
            "```text",
            *log_lines[:80],
            "```",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT, help="Markdown report path")
    args = parser.parse_args()

    android, commands, log_lines = run_hardware_check()
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(render_report(android, commands, log_lines), encoding="utf-8", newline="\n")

    print("Android hardware check simulation passed")
    print("Commands " + " ".join(commands))
    print(android.hardware_text.replace("\n", " | "))
    print(android.link_text.replace("\n", " | "))
    print(android.trace_text.replace("\n", " | "))
    print(android.wiring_text.replace("\n", " | "))
    print(f"hardware check report generated: {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
