"""Verify and report Android command coverage for the HC-05 control APK.

The APK is built directly from Java source in this repository. This script
checks that every firmware Bluetooth command has a visible Android button, that
the APK declares the Bluetooth permissions needed for HC-05 SPP, and that the
UI parser handles every structured response used during classroom acceptance.
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MAIN_ACTIVITY = ROOT / "android" / "app" / "src" / "main" / "java" / "com" / "dkjsiogu" / "mspbluetooth" / "MainActivity.java"
MANIFEST = ROOT / "android" / "app" / "src" / "main" / "AndroidManifest.xml"
DEFAULT_REPORT = ROOT / "docs" / "android_command_coverage_report.md"


@dataclass(frozen=True)
class RequiredCommand:
    command: str
    action: str
    label_hint: str


REQUIRED_COMMANDS = [
    RequiredCommand("p", "play/pause toggle", "Play/Pause"),
    RequiredCommand("s", "stop and rewind current track", "Stop"),
    RequiredCommand("r", "replay current track", "Replay"),
    RequiredCommand("n", "next track", "Next"),
    RequiredCommand("b", "previous track", "Prev"),
    RequiredCommand("+", "volume up", "Vol +"),
    RequiredCommand("-", "volume down", "Vol -"),
    RequiredCommand("m", "mute/restore volume", "Mute"),
    RequiredCommand("o", "cycle playback order", "Order"),
    RequiredCommand("t", "PCM5102A test tone", "Tone"),
    RequiredCommand("i", "firmware info", "Info"),
    RequiredCommand("e", "software-visible self-test", "Selftest"),
    RequiredCommand("l", "scan TRACK01.WAV..TRACK09.WAV", "Track List"),
    RequiredCommand("d", "three-line display frame", "Display"),
    RequiredCommand("?", "current status query", "Status"),
    RequiredCommand("k", "Bluetooth link counters", "Link"),
    RequiredCommand("1", "direct track 1", "Track 1"),
    RequiredCommand("2", "direct track 2", "Track 2"),
    RequiredCommand("3", "direct track 3", "Track 3"),
    RequiredCommand("4", "direct track 4", "Track 4"),
    RequiredCommand("5", "direct track 5", "Track 5"),
    RequiredCommand("6", "direct track 6", "Track 6"),
    RequiredCommand("7", "direct track 7", "Track 7"),
    RequiredCommand("8", "direct track 8", "Track 8"),
    RequiredCommand("9", "direct track 9", "Track 9"),
]

REQUIRED_PARSER_MARKERS = [
    'line.startsWith("status=")',
    'line.startsWith("display 1:")',
    'line.startsWith("display 2:")',
    'line.startsWith("display 3:")',
    'line.startsWith("tracks")',
    'line.startsWith("link ")',
    "updateDashboard",
    "updateDisplayFrame",
    "updateTrackList",
    "updateLinkPanel",
]

REQUIRED_ACCEPTANCE_MARKERS = [
    "acceptanceView",
    "resetAcceptanceSummary",
    "updateAcceptanceSummary",
    "renderAcceptanceSummary",
    "Acceptance 0/8",
    "Acceptance \" + passed + \"/8",
    'line.startsWith("sd mounted")',
    'line.startsWith("info name=")',
    'line.startsWith("selftest bt=ok")',
    'line.startsWith("tone start")',
    'line.startsWith("tone done")',
    'line.startsWith("open TRACK0")',
]

REQUIRED_MANIFEST_MARKERS = [
    'android.permission.BLUETOOTH"',
    'android.permission.BLUETOOTH_ADMIN"',
    'android.permission.ACCESS_FINE_LOCATION"',
    'android.permission.BLUETOOTH_CONNECT"',
    'android.hardware.bluetooth"',
    'android:label="MSP430 Player"',
]

REQUIRED_ACCEPTANCE_COMMANDS = ["h", "i", "e", "l", "d", "?", "t", "1", "p", "+", "n", "b", "o", "3", "k"]


def extract_send_buttons(source: str) -> dict[str, list[str]]:
    """Returns command -> labels from sendButton("label", "command") calls."""

    pattern = re.compile(r'sendButton\("([^"]+)",\s*"([^"]+)"\)')
    commands: dict[str, list[str]] = {}
    for label, command in pattern.findall(source):
        commands.setdefault(command, []).append(label)

    if 'sendButton("Track " + track, String.valueOf(track))' in source:
        for track in range(1, 10):
            commands.setdefault(str(track), []).append(f"Track {track}")
    return commands


def assert_contains(text: str, markers: list[str], label: str) -> None:
    missing = [marker for marker in markers if marker not in text]
    if missing:
        raise AssertionError(f"{label} missing markers: {missing}")


def row(columns: list[object]) -> str:
    return "| " + " | ".join(str(column).replace("|", "\\|") for column in columns) + " |"


def render_report(commands: dict[str, list[str]], source: str, manifest: str) -> str:
    lines = [
        "# Android Command Coverage Report",
        "",
        "Generated by `tools/android_command_coverage.py`. This is a source-level check for the APK before phone installation; real Bluetooth pairing and Android vendor behavior still require a physical phone test.",
        "",
        "## Command Buttons",
        "",
        row(["Firmware command", "Required action", "APK button label"]),
        row(["---", "---", "---"]),
    ]
    for required in REQUIRED_COMMANDS:
        labels = commands.get(required.command, [])
        lines.append(row([f"`{required.command}`", required.action, ", ".join(labels)]))

    lines.extend(
        [
            "",
            "## Structured Response Parsers",
            "",
            row(["Response", "APK handler evidence"]),
            row(["---", "---"]),
            row(["`status=...`", "`updateDashboard` extracts mode, track, volume, order, progress"]),
            row(["`display 1/2/3:...`", "`updateDisplayFrame` renders the three-line display model"]),
            row(["`tracks ...`", "`updateTrackList` renders TRACK01..TRACK09 availability"]),
            row(["`link ...`", "`updateLinkPanel` renders RX/status/display/error counters for Bluetooth round-trip evidence"]),
            row(["Connect bootstrap", "`syncInitialPanels` sends `?`, `l`, and `d` after RFCOMM connect"]),
            row(["Acceptance script", "`Run Acceptance` sends diagnostic, display, tone, and control commands with `TX>` log markers"]),
            row(["Acceptance summary", "`acceptanceView` shows SD, info, selftest, tracks, display, status, tone, and file-open evidence as `Acceptance X/8`"]),
            row(["Acceptance log export", "`Share Log` uses Android `ACTION_SEND` with `EXTRA_TEXT` so logs can be saved and checked on PC"]),
            "",
            "## Bluetooth APK Requirements",
            "",
            row(["Requirement", "Evidence"]),
            row(["---", "---"]),
            row(["Classic SPP UUID", "`00001101-0000-1000-8000-00805F9B34FB`"]),
            row(["Runtime permission path", "`BLUETOOTH_CONNECT` request on Android 12+"]),
            row(["Legacy pairing support", "`BLUETOOTH`, `BLUETOOTH_ADMIN`, and location permission for Android 11-"]),
            row(["Application label", "`MSP430 Player`"]),
            "",
            f"Total command buttons checked: {sum(len(labels) for labels in commands.values())}.",
            "",
        ]
    )
    return "\n".join(lines)


def verify_coverage() -> tuple[dict[str, list[str]], str, str]:
    source = MAIN_ACTIVITY.read_text(encoding="utf-8")
    manifest = MANIFEST.read_text(encoding="utf-8")
    commands = extract_send_buttons(source)

    missing_commands = [required.command for required in REQUIRED_COMMANDS if required.command not in commands]
    if missing_commands:
        raise AssertionError(f"Android APK UI missing command buttons: {missing_commands}")

    wrong_labels = [
        f"{required.command}:{required.label_hint}"
        for required in REQUIRED_COMMANDS
        if required.label_hint not in commands.get(required.command, [])
    ]
    if wrong_labels:
        raise AssertionError(f"Android APK UI missing expected button labels: {wrong_labels}")

    duplicates = {command: labels for command, labels in commands.items() if len(labels) > 1}
    if duplicates:
        raise AssertionError(f"Android APK UI has duplicate command buttons: {duplicates}")

    assert_contains(source, REQUIRED_PARSER_MARKERS, "Android parser")
    assert_contains(source, REQUIRED_ACCEPTANCE_MARKERS, "Android acceptance summary")
    assert_contains(manifest, REQUIRED_MANIFEST_MARKERS, "Android manifest")
    if "createRfcommSocketToServiceRecord(SPP_UUID)" not in source:
        raise AssertionError("Android source does not create an RFCOMM SPP socket")
    if "syncInitialPanels()" not in source:
        raise AssertionError("Android source must run syncInitialPanels after connect")
    for command in ("?", "l", "d"):
        if f'sendCommand("{command}")' not in source:
            raise AssertionError(f"Android source must send {command!r} during initial panel sync")
    if 'commandButton("Run Acceptance"' not in source:
        raise AssertionError("Android source must expose a Run Acceptance button")
    if 'commandButton("Share Log"' not in source:
        raise AssertionError("Android source must expose a Share Log button")
    if "Intent.ACTION_SEND" not in source or "Intent.EXTRA_TEXT" not in source:
        raise AssertionError("Android source must share the acceptance log with ACTION_SEND and EXTRA_TEXT")
    if 'appendLog("TX> " + command)' not in source:
        raise AssertionError("Android source must log transmitted commands with TX> markers")
    for command in REQUIRED_ACCEPTANCE_COMMANDS:
        if f'"{command}"' not in source:
            raise AssertionError(f"Android acceptance script missing command {command!r}")
    return commands, source, manifest


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT, help="Markdown report path")
    args = parser.parse_args()

    commands, source, manifest = verify_coverage()
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(render_report(commands, source, manifest), encoding="utf-8", newline="\n")

    print("Android command coverage passed")
    print(f"command buttons={sum(len(labels) for labels in commands.values())}")
    print(f"coverage report generated: {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
