"""Board-level scenario simulation for the MSP430 environment monitor."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs" / "board_scenario_report.md"
GAS_WARN_ADC = 1800
GAS_STEP_ADC = 300
THRESHOLD_X10 = 300


@dataclass(frozen=True)
class Scenario:
    name: str
    temperature_x10: int
    humidity_x10: int
    gas_adc: int
    distance_mm: int
    dht_ok: bool = True
    distance_ok: bool = True
    mq2_ready: bool = True


@dataclass(frozen=True)
class ScenarioResult:
    scenario: Scenario
    gas_level: int
    alarm_level: int
    oled_lines: tuple[str, str, str, str]
    data_line: str


def x10(value: int) -> str:
    sign = "-" if value < 0 else ""
    value = abs(value)
    return f"{sign}{value // 10}.{value % 10}"


def gas_level(adc: int) -> int:
    if adc <= GAS_WARN_ADC:
        return 0
    return min(5, 1 + ((adc - GAS_WARN_ADC) // GAS_STEP_ADC))


def alarm_level(scenario: Scenario, level: int) -> int:
    temp_level = 0
    if scenario.dht_ok:
        over = scenario.temperature_x10 - THRESHOLD_X10
        if over > 0:
            temp_level = min(5, 1 + (over // 20))
    return max(temp_level, level if scenario.mq2_ready else 0)


def oled_lines(scenario: Scenario, level: int, alarm: int) -> tuple[str, str, str, str]:
    line0 = f"T:{x10(scenario.temperature_x10)}C H:{scenario.humidity_x10 // 10}%"
    line1 = f"GAS:{scenario.gas_adc} L:{level}"
    distance = str(scenario.distance_mm) if scenario.distance_ok else "----"
    line2 = f"D:{distance}MM"
    line3 = f"TH:{x10(THRESHOLD_X10)} ALM:{alarm}"
    return line0, line1, line2, line3


def data_line(scenario: Scenario, level: int, alarm: int) -> str:
    return (
        f"DATA T={x10(scenario.temperature_x10)} H={scenario.humidity_x10 // 10} "
        f"GAS={scenario.gas_adc} L={level} D={scenario.distance_mm} "
        f"TH={x10(THRESHOLD_X10)} ALM={alarm}"
    )


def run_scenario(scenario: Scenario) -> ScenarioResult:
    level = gas_level(scenario.gas_adc)
    alarm = alarm_level(scenario, level)
    lines = oled_lines(scenario, level, alarm)
    for line in lines:
        if len(line) > 21:
            raise AssertionError(f"OLED line too long in {scenario.name}: {line}")
    return ScenarioResult(scenario, level, alarm, lines, data_line(scenario, level, alarm))


def row(columns: list[object]) -> str:
    return "| " + " | ".join(str(column).replace("|", "\\|") for column in columns) + " |"


def render_report(results: list[ScenarioResult]) -> str:
    lines = [
        "# Board Scenario Simulation",
        "",
        "Generated by `tools/board_scenario_sim.py`. It checks the firmware-visible behavior of sensor values, OLED text, Bluetooth telemetry, and alarm levels.",
        "",
        row(["Scenario", "T", "H", "Gas ADC", "Distance", "Gas L", "Alarm", "OLED"]),
        row(["---", "---", "---", "---", "---", "---", "---", "---"]),
    ]
    for result in results:
        scenario = result.scenario
        lines.append(
            row(
                [
                    scenario.name,
                    x10(scenario.temperature_x10),
                    scenario.humidity_x10 // 10,
                    scenario.gas_adc,
                    scenario.distance_mm if scenario.distance_ok else "timeout",
                    result.gas_level,
                    result.alarm_level,
                    " / ".join(result.oled_lines),
                ]
            )
        )

    lines.extend(["", "## Bluetooth DATA Lines", "", "```text"])
    lines.extend(result.data_line for result in results)
    lines.extend(["```", ""])
    return "\n".join(lines)


def main() -> int:
    scenarios = [
        Scenario("normal room", 263, 580, 1250, 342),
        Scenario("temperature warning", 326, 620, 1300, 310),
        Scenario("gas warning", 282, 590, 2450, 280),
        Scenario("combined danger", 388, 700, 3600, 190),
        Scenario("ultrasonic timeout", 251, 530, 1100, 0, distance_ok=False),
    ]
    results = [run_scenario(scenario) for scenario in scenarios]

    expected = {
        "normal room": 0,
        "temperature warning": 2,
        "gas warning": 3,
        "combined danger": 5,
        "ultrasonic timeout": 0,
    }
    for result in results:
        wanted = expected[result.scenario.name]
        if result.alarm_level != wanted:
            raise AssertionError(f"{result.scenario.name} alarm={result.alarm_level}, expected {wanted}")

    REPORT.write_text(render_report(results), encoding="utf-8")
    print("board scenario simulation passed")
    print(f"report generated: {REPORT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
