"""Threshold-adjustment simulation for EC11 and Bluetooth commands."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs" / "encoder_threshold_report.md"
DEFAULT_THRESHOLD_X10 = 300
STEP_X10 = 5


@dataclass(frozen=True)
class Action:
    source: str
    delta_x10: int
    expected_x10: int
    trace: str


def x10(value: int) -> str:
    sign = "-" if value < 0 else ""
    value = abs(value)
    return f"{sign}{value // 10}.{value % 10}"


def row(columns: list[object]) -> str:
    return "| " + " | ".join(str(column).replace("|", "\\|") for column in columns) + " |"


def main() -> int:
    threshold = DEFAULT_THRESHOLD_X10
    trace: list[str] = []
    actions = [
        Action("EC11 clockwise", STEP_X10, 305, "enc:+"),
        Action("EC11 clockwise", STEP_X10, 310, "enc:+"),
        Action("Bluetooth T-", -STEP_X10, 305, "bt:T-"),
        Action("EC11 counterclockwise", -STEP_X10, 300, "enc:-"),
        Action("Bluetooth T+", STEP_X10, 305, "bt:T+"),
    ]

    rows = []
    for action in actions:
        threshold += action.delta_x10
        trace.insert(0, action.trace)
        trace = trace[:6]
        if threshold != action.expected_x10:
            raise AssertionError(f"{action.source} threshold={threshold}, expected {action.expected_x10}")
        rows.append([action.source, f"{action.delta_x10 / 10:+.1f} C", x10(threshold), action.trace])

    threshold = int(round(32.0 * 10))
    trace.insert(0, "bt:SET")
    if threshold != 320:
        raise AssertionError("SETT=32.0 parse failed")
    rows.append(["Bluetooth SETT=32.0", "direct", x10(threshold), "bt:SET"])

    report = [
        "# Encoder Threshold Simulation",
        "",
        "Generated by `tools/encoder_threshold_sim.py`. It checks that local EC11 rotation and Bluetooth threshold commands use the same 0.5 C step model.",
        "",
        row(["Action", "Delta", "Threshold", "Trace"]),
        row(["---", "---", "---", "---"]),
    ]
    report.extend(row(item) for item in rows)
    report.extend(["", f"Final trace window: `{', '.join(trace[:6])}`", ""])
    REPORT.write_text("\n".join(report), encoding="utf-8")
    print("encoder threshold simulation passed")
    print(f"report generated: {REPORT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
