"""End-to-end demo simulator for APK button presses and firmware responses.

This script stitches together the phone-side parser model and the firmware
Bluetooth command model. It verifies the classroom demonstration path from APK
button press, to HC-05 command byte, to firmware response text, to visible
Android dashboard/display/track-list updates.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

from android_ui_parser_sim import AndroidUiState, handle_incoming_text
from bluetooth_protocol_sim import SimulatedPlayer


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REPORT = ROOT / "docs" / "end_to_end_demo_report.md"


@dataclass(frozen=True)
class DemoStep:
    label: str
    command: str
    note: str


@dataclass
class DemoSnapshot:
    label: str
    command: str
    note: str
    responses: list[str]
    dashboard: str
    display: str
    tracks: str
    link: str


DEMO_STEPS = [
    DemoStep("Connect auto status", "?", "APK queries current state immediately after RFCOMM connect"),
    DemoStep("Connect auto track list", "l", "APK syncs TRACKxx.WAV availability immediately after connect"),
    DemoStep("Connect auto display", "d", "APK syncs the three-line display frame immediately after connect"),
    DemoStep("Play/Pause", "p", "firmware starts playback and immediately reports status"),
    DemoStep("Vol +", "+", "firmware raises software volume and immediately reports status"),
    DemoStep("Next", "n", "firmware skips to the next playable track and immediately reports status"),
    DemoStep("Prev", "b", "firmware returns to the previous playable track and immediately reports status"),
    DemoStep("Order", "o", "firmware switches repeat_all to repeat_one and immediately reports status"),
    DemoStep("Tone", "t", "firmware emits a DAC test tone transcript and reports status"),
    DemoStep("Track 3", "3", "direct track button opens TRACK03.WAV and immediately reports status"),
    DemoStep("Link", "k", "firmware reports Bluetooth RX, status, display, bad-command, and last-command counters"),
]


def fragmented_uart_feed(android: AndroidUiState, responses: list[str]) -> None:
    """Feeds firmware response lines to the Android parser in uneven chunks."""

    stream = "".join(f"{line}\r\n" for line in responses)
    cut_points = [3, 11, 23, 41, 67]
    start = 0
    for cut in cut_points:
        if start >= len(stream):
            return
        handle_incoming_text(android, stream[start:cut])
        start = cut
    if start < len(stream):
        handle_incoming_text(android, stream[start:])


def run_demo() -> list[DemoSnapshot]:
    player = SimulatedPlayer()
    android = AndroidUiState()
    snapshots: list[DemoSnapshot] = []

    for step in DEMO_STEPS:
        before = len(player.transcript)
        player.send(step.command)
        responses = player.transcript[before:]
        fragmented_uart_feed(android, responses)
        snapshots.append(
            DemoSnapshot(
                label=step.label,
                command=step.command,
                note=step.note,
                responses=responses,
                dashboard=android.dashboard_text,
                display=android.display_text,
                tracks=android.track_list_text,
                link=android.link_text,
            )
        )

    expected_dashboard = "Mode: playing\nTrack: 3\nVolume: 19\nOrder: repeat_one\nProgress: 0%"
    expected_display = "Display frame\nplaying T3 V19 ONE\nSD:OK WAV:OPEN\n16000Hz 2ch P0%"
    expected_tracks = "Tracks\n1: ok  2: --  3: ok\n4: --  5: --  6: --\n7: --  8: --  9: --"

    if android.dashboard_text != expected_dashboard:
        raise AssertionError(f"final dashboard mismatch: {android.dashboard_text!r}")
    if android.display_text != expected_display:
        raise AssertionError(f"final display mismatch: {android.display_text!r}")
    if android.track_list_text != expected_tracks:
        raise AssertionError(f"final track list mismatch: {android.track_list_text!r}")
    if "RX: 11" not in android.link_text or "Last: k" not in android.link_text:
        raise AssertionError(f"final link panel mismatch: {android.link_text!r}")
    if android.rx_line_buffer:
        raise AssertionError(f"Android line buffer should be empty, got {android.rx_line_buffer!r}")
    if not any("tone done" in snapshot.responses for snapshot in snapshots):
        raise AssertionError("tone command transcript was not observed")

    return snapshots


def row(columns: list[object]) -> str:
    return "| " + " | ".join(str(column).replace("|", "\\|").replace("\n", " / ") for column in columns) + " |"


def render_report(snapshots: list[DemoSnapshot]) -> str:
    lines = [
        "# End-to-End Demo Simulation Report",
        "",
        "Generated by `tools/end_to_end_demo_sim.py`. It proves the software-visible demo path from Android button commands through simulated HC-05 UART responses into the Android dashboard, display frame, and track-list panels. State-changing commands are expected to emit immediate `status=...` and `display 1/2/3:...` lines, so the phone UI updates without separate Status or Display button presses. Real phone pairing, real UART voltage levels, TF-card electrical I/O, DAC output, and amplifier/headphone audio still require board testing.",
        "",
        row(["Step", "APK command", "Purpose", "Firmware responses", "Visible phone state"]),
        row(["---", "---", "---", "---", "---"]),
    ]
    for snapshot in snapshots:
        visible = (
            snapshot.dashboard.replace("\n", " / ")
            + " | "
            + snapshot.display.replace("\n", " / ")
            + " | "
            + snapshot.tracks.replace("\n", " / ")
            + " | "
            + snapshot.link.replace("\n", " / ")
        )
        lines.append(row([snapshot.label, f"`{snapshot.command}`", snapshot.note, " -> ".join(snapshot.responses), visible]))

    lines.extend(
        [
            "",
            "## Final Visible State",
            "",
            row(["Panel", "Text"]),
            row(["---", "---"]),
            row(["Dashboard", snapshots[-1].dashboard]),
            row(["Display frame", snapshots[-1].display]),
            row(["Track list", snapshots[-1].tracks]),
            row(["Link", snapshots[-1].link]),
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT, help="Markdown report path")
    args = parser.parse_args()

    snapshots = run_demo()
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(render_report(snapshots), encoding="utf-8", newline="\n")

    print("end-to-end demo simulation passed")
    print(snapshots[-1].dashboard.replace("\n", " | "))
    print(snapshots[-1].display.replace("\n", " | "))
    print(snapshots[-1].link.replace("\n", " | "))
    print(f"demo report generated: {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
