"""Verify optional e-paper driver wiring, command flow, and payload size.

The real panel is slow and requires hardware, so this script checks the source
contract that can be proven on the PC: the driver is compiled by the makefile,
the default build keeps it disabled, the optional pin map is documented, and a
single three-line refresh would send exactly one 296x128 black/white RAM image.
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REPORT = ROOT / "docs" / "epaper_driver_report.md"

WIDTH_PIXELS = 296
HEIGHT_PIXELS = 128
ROW_BYTES = WIDTH_PIXELS // 8
FRAME_BYTES = ROW_BYTES * HEIGHT_PIXELS

REQUIRED_SOURCE_MARKERS = [
    "EPAPER_CMD_WRITE_BW_RAM",
    "EPAPER_CMD_DISPLAY_UPDATE",
    "EPAPER_CMD_MASTER_ACTIVATE",
    "EPAPER_CMD_SET_RAM_X",
    "EPAPER_CMD_SET_RAM_Y",
    "epaper_panel_show_frame",
    "epaper_frame_byte",
]

REQUIRED_PIN_MARKERS = [
    "EPAPER_SCK_BIT",
    "EPAPER_MOSI_BIT",
    "EPAPER_CS_BIT",
    "EPAPER_DC_BIT",
    "EPAPER_RST_BIT",
    "EPAPER_BUSY_BIT",
]


@dataclass(frozen=True)
class TraceStep:
    name: str
    command: str
    data_bytes: int
    purpose: str


def read(relative: str) -> str:
    """Reads a repository text file as UTF-8-compatible text."""

    return (ROOT / relative).read_text(encoding="utf-8", errors="ignore")


def assert_contains(text: str, markers: list[str], label: str) -> None:
    """Raises when any required marker is absent from text."""

    missing = [marker for marker in markers if marker not in text]
    if missing:
        raise AssertionError(f"{label} missing markers: {missing}")


def parse_define_value(header: str, name: str) -> str:
    """Returns the raw value for a simple #define."""

    match = re.search(rf"^#define\s+{re.escape(name)}\s+(.+)$", header, re.M)
    if not match:
        raise AssertionError(f"missing #define {name}")
    return match.group(1).strip()


def build_refresh_trace() -> list[TraceStep]:
    """Builds the expected full-refresh command sequence."""

    return [
        TraceStep("Power on", "0x04", 0, "enable panel charge pumps"),
        TraceStep("Set X window", "0x44", 2, "select 37 horizontal RAM bytes"),
        TraceStep("Set Y window", "0x45", 4, "select 128 vertical scan rows"),
        TraceStep("Set X counter", "0x4E", 1, "rewind RAM write X address"),
        TraceStep("Set Y counter", "0x4F", 2, "rewind RAM write Y address"),
        TraceStep("Write BW RAM", "0x24", FRAME_BYTES, "stream one packed 296x128 frame"),
        TraceStep("Display update", "0x22", 1, "request black/white refresh waveform"),
        TraceStep("Master activate", "0x20", 0, "start physical panel refresh"),
        TraceStep("Power off", "0x02", 0, "reduce panel idle current"),
    ]


def verify_driver_contract() -> list[TraceStep]:
    """Checks source-level facts that prove the optional driver is wired in."""

    source = read("drivers/epaper_panel.c")
    header = read("drivers/epaper_panel.h")
    pins = read("drivers/board_pins.h")
    config = read("drivers/platform_config.h")
    makefile = read("Debug/makefile")
    main = read("main.c")
    player = read("application/audio_player.c")

    assert_contains(source, REQUIRED_SOURCE_MARKERS, "e-paper driver")
    assert_contains(pins, REQUIRED_PIN_MARKERS, "e-paper pin map")
    if "epaper_panel.obj" not in makefile:
        raise AssertionError("Debug/makefile must compile epaper_panel.obj")
    if "epaper_panel_init();" not in main:
        raise AssertionError("main.c must initialize the optional e-paper panel")
    if "epaper_panel_show_frame(&frame);" not in player:
        raise AssertionError("audio_player.c must feed the display frame to e-paper")

    if parse_define_value(config, "PLAYER_ENABLE_EPAPER_PANEL") != "0u":
        raise AssertionError("default firmware must keep PLAYER_ENABLE_EPAPER_PANEL at 0u")
    if parse_define_value(header, "EPAPER_WIDTH_PIXELS") != "296u":
        raise AssertionError("EPAPER_WIDTH_PIXELS must match the simulated panel")
    if parse_define_value(header, "EPAPER_HEIGHT_PIXELS") != "128u":
        raise AssertionError("EPAPER_HEIGHT_PIXELS must match the simulated panel")

    return build_refresh_trace()


def row(columns: list[object]) -> str:
    """Formats one Markdown table row."""

    return "| " + " | ".join(str(column).replace("|", "\\|") for column in columns) + " |"


def render_report(trace: list[TraceStep]) -> str:
    """Renders a Markdown evidence report for the optional e-paper driver."""

    total_data = sum(step.data_bytes for step in trace)
    lines = [
        "# Optional E-Paper Driver Report",
        "",
        "Generated by `tools/epaper_driver_trace_sim.py`. It verifies the optional 296x128 SPI e-paper driver at source level. The default firmware keeps `PLAYER_ENABLE_EPAPER_PANEL` disabled so the audio player remains the main path; enabling it requires real P6.x wiring and physical panel testing.",
        "",
        row(["Item", "Value"]),
        row(["---", "---"]),
        row(["Panel geometry", f"{WIDTH_PIXELS}x{HEIGHT_PIXELS} pixels"]),
        row(["Packed row bytes", ROW_BYTES]),
        row(["Black/white RAM payload", FRAME_BYTES]),
        row(["Default build", "`PLAYER_ENABLE_EPAPER_PANEL=0u`"]),
        row(["Optional pins", "`P6.0=SCK, P6.1=MOSI, P6.2=CS, P6.3=DC, P6.4=RST, P6.5=BUSY`"]),
        "",
        "## Refresh Trace",
        "",
        row(["Step", "Command", "Data bytes", "Purpose"]),
        row(["---", "---", "---", "---"]),
    ]
    for step in trace:
        lines.append(row([step.name, step.command, step.data_bytes, step.purpose]))
    lines.extend(
        [
            "",
            f"Total command data bytes in one full refresh: {total_data}.",
            "",
            "The visual content is the same `DisplayFrame` already checked by Bluetooth, Android parser, and PGM preview simulations.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT, help="Markdown report path")
    args = parser.parse_args()

    trace = verify_driver_contract()
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(render_report(trace), encoding="utf-8", newline="\n")

    print("optional e-paper driver trace passed")
    print(f"geometry={WIDTH_PIXELS}x{HEIGHT_PIXELS} row_bytes={ROW_BYTES} frame_bytes={FRAME_BYTES}")
    print(f"e-paper driver report generated: {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
