"""Host simulation for the internal Flash history log contract."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs" / "flash_log_report.md"
FLASH_BYTES = 384
RECORD_BYTES = 24
CAPACITY = FLASH_BYTES // RECORD_BYTES
MAGIC = 0xE551


@dataclass
class Record:
    magic: int
    seq: int
    uptime_s: int
    temperature_x10: int
    humidity_x10: int
    gas_adc: int
    distance_mm: int
    threshold_x10: int
    alarm_level: int
    flags: int
    crc: int = 0

    def payload_bytes(self) -> list[int]:
        fields = [
            self.magic,
            self.seq & 0xFFFF,
            (self.seq >> 16) & 0xFFFF,
            self.uptime_s & 0xFFFF,
            (self.uptime_s >> 16) & 0xFFFF,
            self.temperature_x10 & 0xFFFF,
            self.humidity_x10,
            self.gas_adc,
            self.distance_mm,
            self.threshold_x10 & 0xFFFF,
            self.alarm_level | (self.flags << 8),
        ]
        data: list[int] = []
        for field in fields:
            data.append(field & 0xFF)
            data.append((field >> 8) & 0xFF)
        return data

    def compute_crc(self) -> int:
        return sum(self.payload_bytes()) & 0xFFFF


class FlashLog:
    def __init__(self) -> None:
        self.records: list[Record] = []
        self.next_seq = 1
        self.erase_count = 0

    def clear(self) -> None:
        self.records.clear()
        self.next_seq = 1
        self.erase_count += 1

    def append(self, temperature_x10: int, gas_adc: int, alarm_level: int) -> None:
        if len(self.records) >= CAPACITY:
            self.clear()
        record = Record(MAGIC, self.next_seq, self.next_seq * 10, temperature_x10, 560, gas_adc, 300, 300, alarm_level, 0x07)
        record.crc = record.compute_crc()
        self.records.append(record)
        self.next_seq += 1

    def read(self, index: int) -> Record | None:
        if index <= 0 or index > len(self.records):
            return None
        record = self.records[index - 1]
        if record.magic != MAGIC or record.compute_crc() != record.crc:
            return None
        return record


def row(columns: list[object]) -> str:
    return "| " + " | ".join(str(column).replace("|", "\\|") for column in columns) + " |"


def main() -> int:
    log = FlashLog()
    for index in range(CAPACITY + 3):
        log.append(250 + index, 1200 + index * 20, min(5, index // 3))

    if len(log.records) != 3:
        raise AssertionError(f"wrap erase should leave 3 records, got {len(log.records)}")
    if log.erase_count != 1:
        raise AssertionError(f"expected one erase, got {log.erase_count}")
    if log.read(1) is None or log.read(3) is None or log.read(4) is not None:
        raise AssertionError("history read bounds failed")

    corrupt = log.records[1]
    corrupt.crc ^= 0x55
    if log.read(2) is not None:
        raise AssertionError("CRC corruption was not detected")

    report = [
        "# Flash Log Simulation",
        "",
        "Generated by `tools/flash_log_sim.py`. It mirrors the fixed-record append, full erase, sequence, bounds, and CRC behavior of `drivers/flash_log.c`.",
        "",
        row(["Item", "Value"]),
        row(["---", "---"]),
        row(["Information Flash bytes", FLASH_BYTES]),
        row(["Record bytes", RECORD_BYTES]),
        row(["Computed capacity", CAPACITY]),
        row(["Erase count after capacity+3 appends", log.erase_count]),
        row(["Remaining readable records after wrap", len(log.records)]),
        row(["CRC corruption check", "PASS"]),
        "",
    ]
    REPORT.write_text("\n".join(report), encoding="utf-8")
    print("flash log simulation passed")
    print(f"report generated: {REPORT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
