"""Simulate player status LED patterns.

The real firmware drives P1.0 through board_status_led_set/toggle. This model
checks the higher-level timing contract: playing blinks fast, paused blinks
slowly, stopped stays on, and errors use a repeating double-blink pattern.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REPORT = ROOT / "docs" / "status_led_report.md"

PLAYING_MS = 200
PAUSED_MS = 1000
ERROR_STEP_MS = 150


@dataclass
class LedModel:
    """LedModel: host-side mirror of the firmware LED pattern state."""

    mode: str = "stopped"
    led_mode: str = "stopped"
    stamp_ms: int = 0
    error_step: int = 0
    led_on: int = 1
    timeline: list[tuple[int, int]] = field(default_factory=list)

    def reset_pattern(self, now_ms: int) -> None:
        """Restarts the LED pattern after a mode change."""

        self.led_mode = self.mode
        self.stamp_ms = now_ms
        self.error_step = 0
        self.led_on = 0 if self.mode == "paused" else 1
        self.timeline.append((now_ms, self.led_on))

    def set_mode(self, mode: str, now_ms: int) -> None:
        """Changes playback mode and restarts the visible LED pattern."""

        self.mode = mode
        self.reset_pattern(now_ms)

    def elapsed(self, now_ms: int, interval_ms: int) -> bool:
        """Returns true once interval_ms elapsed and refreshes stamp_ms."""

        if now_ms - self.stamp_ms >= interval_ms:
            self.stamp_ms = now_ms
            return True
        return False

    def set_led(self, now_ms: int, on: int) -> None:
        """Writes the LED state and records changes."""

        if self.led_on != on:
            self.led_on = on
            self.timeline.append((now_ms, self.led_on))

    def toggle(self, now_ms: int) -> None:
        """Toggles the LED state and records the transition."""

        self.led_on = 0 if self.led_on else 1
        self.timeline.append((now_ms, self.led_on))

    def poll(self, now_ms: int) -> None:
        """Applies one firmware-style LED update at now_ms."""

        if self.led_mode != self.mode:
            self.reset_pattern(now_ms)

        if self.mode == "playing":
            if self.elapsed(now_ms, PLAYING_MS):
                self.toggle(now_ms)
        elif self.mode == "paused":
            if self.elapsed(now_ms, PAUSED_MS):
                self.toggle(now_ms)
        elif self.mode == "error":
            if self.elapsed(now_ms, ERROR_STEP_MS):
                self.error_step = (self.error_step + 1) & 0x07
                self.set_led(now_ms, 1 if self.error_step in (0, 2) else 0)
        else:
            self.set_led(now_ms, 1)


def run_mode(mode: str, duration_ms: int, step_ms: int = 50) -> LedModel:
    """Runs one LED mode simulation and returns the model."""

    model = LedModel()
    model.set_mode(mode, 0)
    for now_ms in range(step_ms, duration_ms + step_ms, step_ms):
        model.poll(now_ms)
    return model


def transition_deltas(model: LedModel) -> list[int]:
    """Returns time deltas between LED transitions."""

    return [now - previous for (previous, _), (now, _) in zip(model.timeline, model.timeline[1:])]


def assert_patterns() -> dict[str, LedModel]:
    """Runs all pattern checks."""

    playing = run_mode("playing", 1000)
    paused = run_mode("paused", 2500)
    stopped = run_mode("stopped", 1500)
    error = run_mode("error", 1500)

    if transition_deltas(playing)[:4] != [200, 200, 200, 200]:
        raise AssertionError(f"playing LED cadence mismatch: {playing.timeline}")
    if transition_deltas(paused)[:2] != [1000, 1000]:
        raise AssertionError(f"paused LED cadence mismatch: {paused.timeline}")
    if stopped.timeline != [(0, 1)]:
        raise AssertionError(f"stopped LED should stay on: {stopped.timeline}")
    expected_error = [(0, 1), (150, 0), (300, 1), (450, 0), (1200, 1), (1350, 0)]
    if error.timeline[:6] != expected_error:
        raise AssertionError(f"error LED double-blink mismatch: {error.timeline}")

    return {
        "playing": playing,
        "paused": paused,
        "stopped": stopped,
        "error": error,
    }


def row(columns: list[object]) -> str:
    """Formats one Markdown table row."""

    return "| " + " | ".join(str(column).replace("|", "\\|") for column in columns) + " |"


def render_report(models: dict[str, LedModel]) -> str:
    """Renders the LED pattern report."""

    lines = [
        "# Status LED Pattern Report",
        "",
        "Generated by `tools/status_led_pattern_sim.py`. It validates the software-visible P1.0 LED patterns used for first-stage board bring-up before Bluetooth or audio is connected.",
        "",
        row(["Mode", "Expected effect", "Observed transitions"]),
        row(["---", "---", "---"]),
        row(["playing", "fast blink every 200 ms", models["playing"].timeline]),
        row(["paused", "slow blink every 1000 ms", models["paused"].timeline]),
        row(["stopped", "steady on", models["stopped"].timeline]),
        row(["error", "repeating double blink", models["error"].timeline]),
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    """CLI entry point."""

    parser = argparse.ArgumentParser()
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT, help="Markdown report path")
    args = parser.parse_args()

    models = assert_patterns()
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(render_report(models), encoding="utf-8", newline="\n")

    print("status LED pattern simulation passed")
    for mode, model in models.items():
        print(f"{mode}: {model.timeline}")
    print(f"status LED report generated: {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
